package vos.hibernate;

// Generated 16/05/2007 16:47:40 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	// Fields    

	private long id;

	private String nome;

	private String descricao;

	private Set produtos = new HashSet(0);

	// Constructors

	/** default constructor */
	public Categoria() {
	}

	/** minimal constructor */
	public Categoria(long id, String nome, String descricao) {
		this.id = id;
		this.nome = nome;
		this.descricao = descricao;
	}

	/** full constructor */
	public Categoria(long id, String nome, String descricao, Set produtos) {
		this.id = id;
		this.nome = nome;
		this.descricao = descricao;
		this.produtos = produtos;
	}

	// Property accessors
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Set getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set produtos) {
		this.produtos = produtos;
	}

}
