package vos.hibernate;

// Generated 16/05/2007 16:47:40 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido implements java.io.Serializable {

	// Fields    

	private long id;

	private Usuario usuario;

	private String rua;

	private int numero;

	private String cidade;

	private String estado;

	private String cep;

	private Set produtoPedidos = new HashSet(0);

	// Constructors

	/** default constructor */
	public Pedido() {
	}

	/** minimal constructor */
	public Pedido(long id, Usuario usuario, String rua, int numero,
			String cidade, String estado, String cep) {
		this.id = id;
		this.usuario = usuario;
		this.rua = rua;
		this.numero = numero;
		this.cidade = cidade;
		this.estado = estado;
		this.cep = cep;
	}

	/** full constructor */
	public Pedido(long id, Usuario usuario, String rua, int numero,
			String cidade, String estado, String cep, Set produtoPedidos) {
		this.id = id;
		this.usuario = usuario;
		this.rua = rua;
		this.numero = numero;
		this.cidade = cidade;
		this.estado = estado;
		this.cep = cep;
		this.produtoPedidos = produtoPedidos;
	}

	// Property accessors
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getRua() {
		return this.rua;
	}

	public void setRua(String rua) {
		this.rua = rua;
	}

	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	public Set getProdutoPedidos() {
		return this.produtoPedidos;
	}

	public void setProdutoPedidos(Set produtoPedidos) {
		this.produtoPedidos = produtoPedidos;
	}

}
