package vos.hibernate;

// Generated 16/05/2007 16:47:40 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto implements java.io.Serializable {

	// Fields    

	private long id;

	private String nome;

	private String descricao;

	private String cor;

	private double peso;

	private double preco;

	private Set categorias = new HashSet(0);

	private Set produtoPedidos = new HashSet(0);

	private Set promocaos = new HashSet(0);

	// Constructors

	/** default constructor */
	public Produto() {
	}

	/** minimal constructor */
	public Produto(long id, String nome, String descricao, String cor,
			double peso, double preco) {
		this.id = id;
		this.nome = nome;
		this.descricao = descricao;
		this.cor = cor;
		this.peso = peso;
		this.preco = preco;
	}

	/** full constructor */
	public Produto(long id, String nome, String descricao, String cor,
			double peso, double preco, Set categorias, Set produtoPedidos,
			Set promocaos) {
		this.id = id;
		this.nome = nome;
		this.descricao = descricao;
		this.cor = cor;
		this.peso = peso;
		this.preco = preco;
		this.categorias = categorias;
		this.produtoPedidos = produtoPedidos;
		this.promocaos = promocaos;
	}

	// Property accessors
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public String getCor() {
		return this.cor;
	}

	public void setCor(String cor) {
		this.cor = cor;
	}

	public double getPeso() {
		return this.peso;
	}

	public void setPeso(double peso) {
		this.peso = peso;
	}

	public double getPreco() {
		return this.preco;
	}

	public void setPreco(double preco) {
		this.preco = preco;
	}

	public Set getCategorias() {
		return this.categorias;
	}

	public void setCategorias(Set categorias) {
		this.categorias = categorias;
	}

	public Set getProdutoPedidos() {
		return this.produtoPedidos;
	}

	public void setProdutoPedidos(Set produtoPedidos) {
		this.produtoPedidos = produtoPedidos;
	}

	public Set getPromocaos() {
		return this.promocaos;
	}

	public void setPromocaos(Set promocaos) {
		this.promocaos = promocaos;
	}

}
