package vos.hibernate;

// Generated 16/05/2007 16:47:40 by Hibernate Tools 3.2.0.beta8

/**
 * ProdutoPedidoId generated by hbm2java
 */
public class ProdutoPedidoId implements java.io.Serializable {

	// Fields    

	private long pedido;

	private long produto;

	// Constructors

	/** default constructor */
	public ProdutoPedidoId() {
	}

	/** full constructor */
	public ProdutoPedidoId(long pedido, long produto) {
		this.pedido = pedido;
		this.produto = produto;
	}

	// Property accessors
	public long getPedido() {
		return this.pedido;
	}

	public void setPedido(long pedido) {
		this.pedido = pedido;
	}

	public long getProduto() {
		return this.produto;
	}

	public void setProduto(long produto) {
		this.produto = produto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProdutoPedidoId))
			return false;
		ProdutoPedidoId castOther = (ProdutoPedidoId) other;

		return (this.getPedido() == castOther.getPedido())
				&& (this.getProduto() == castOther.getProduto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPedido();
		result = 37 * result + (int) this.getProduto();
		return result;
	}

}
