package vos.hibernate;

// Generated 16/05/2007 16:47:40 by Hibernate Tools 3.2.0.beta8

/**
 * RoleId generated by hbm2java
 */
public class RoleId implements java.io.Serializable {

	// Fields    

	private String login;

	private String role;

	// Constructors

	/** default constructor */
	public RoleId() {
	}

	/** full constructor */
	public RoleId(String login, String role) {
		this.login = login;
		this.role = role;
	}

	// Property accessors
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleId))
			return false;
		RoleId castOther = (RoleId) other;

		return ((this.getLogin() == castOther.getLogin()) || (this.getLogin() != null
				&& castOther.getLogin() != null && this.getLogin().equals(
				castOther.getLogin())))
				&& ((this.getRole() == castOther.getRole()) || (this.getRole() != null
						&& castOther.getRole() != null && this.getRole()
						.equals(castOther.getRole())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLogin() == null ? 0 : this.getLogin().hashCode());
		result = 37 * result
				+ (getRole() == null ? 0 : this.getRole().hashCode());
		return result;
	}

}
