package vos.hibernate;

// Generated 16/05/2007 16:47:40 by Hibernate Tools 3.2.0.beta8

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	// Fields    

	private RoleId id;

	private Usuario usuario;

	// Constructors

	/** default constructor */
	public Role() {
	}

	/** full constructor */
	public Role(RoleId id, Usuario usuario) {
		this.id = id;
		this.usuario = usuario;
	}

	// Property accessors
	public RoleId getId() {
		return this.id;
	}

	public void setId(RoleId id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
