package vos.hibernate;

// Generated 16/05/2007 16:47:40 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	// Fields    

	private String login;

	private String senha;

	private String nome;

	private String cartao;

	private String email;

	private String telefone;

	private Set pedidos = new HashSet(0);

	private Set roles = new HashSet(0);

	// Constructors

	/** default constructor */
	public Usuario() {
	}

	/** minimal constructor */
	public Usuario(String login, String senha, String nome, String cartao,
			String email, String telefone) {
		this.login = login;
		this.senha = senha;
		this.nome = nome;
		this.cartao = cartao;
		this.email = email;
		this.telefone = telefone;
	}

	/** full constructor */
	public Usuario(String login, String senha, String nome, String cartao,
			String email, String telefone, Set pedidos, Set roles) {
		this.login = login;
		this.senha = senha;
		this.nome = nome;
		this.cartao = cartao;
		this.email = email;
		this.telefone = telefone;
		this.pedidos = pedidos;
		this.roles = roles;
	}

	// Property accessors
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCartao() {
		return this.cartao;
	}

	public void setCartao(String cartao) {
		this.cartao = cartao;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public Set getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set pedidos) {
		this.pedidos = pedidos;
	}

	public Set getRoles() {
		return this.roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

}
